# Generated by Django 2.2.20 on 2021-11-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0002_auto_20211101_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alexadashcams.Product'),
        ),
    ]
