# Generated by Django 2.2.20 on 2021-11-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
