# Generated by Django 2.2.20 on 2021-11-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0006_auto_20211101_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
