# Generated by Django 2.2.20 on 2021-11-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0007_auto_20211101_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
