# Generated by Django 2.2.20 on 2021-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0009_auto_20211101_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
