# Generated by Django 3.2.6 on 2021-11-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0014_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
