# Generated by Django 3.2.6 on 2021-11-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexadashcams', '0015_rename_images_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
