# Generated by Django 3.2.9 on 2021-11-10 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name_id', models.CharField(max_length=100)),
                ('order_address', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_Total', models.IntegerField()),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
