# Generated by Django 3.2.9 on 2022-02-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profile_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='staff_pics'),
        ),
    ]
