# Generated by Django 3.2.9 on 2022-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staffprofile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='names',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
