# Generated by Django 3.2.9 on 2022-02-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220214_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TISNStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=100)),
                ('names', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, choices=[('Oncology Nursing', 'Oncology Nursing'), ('Critical Care Nursing', 'Critical Care Nursing')], max_length=100)),
                ('start_date', models.DateField(blank=True, max_length=100)),
                ('end_date', models.DateField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('images', models.ImageField(default='default.jpg', upload_to='tisn_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='directorate',
            field=models.CharField(blank=True, choices=[('Clinical_Services', 'Clinical Services'), ('Nursing_Services', 'Nursing Services'), ('Training, Research & Innovations', 'Training, Research & Innovations'), ('IMIC', 'IMIC'), ('Human_Resource_Development', 'Human Resource Development'), ('Planning, Strategy & Development', 'Planning, Strategy & Development'), ('Partnerships_Linkages_&_Resource_Mobilisation', 'Partnerships, Linkages & Resource Mobilisation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='directorate',
            field=models.CharField(blank=True, choices=[('Clinical_Services', 'Clinical Services'), ('Nursing_Services', 'Nursing Services'), ('Training, Research & Innovations', 'Training, Research & Innovations'), ('IMIC', 'IMIC'), ('Human_Resource_Development', 'Human Resource Development'), ('Planning, Strategy & Development', 'Planning, Strategy & Development'), ('Partnerships_Linkages_&_Resource_Mobilisation', 'Partnerships, Linkages & Resource Mobilisation')], max_length=100),
        ),
    ]
