# Generated by Django 3.2.9 on 2022-02-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='StaffProfile',
        ),
    ]
