# Generated by Django 3.2.9 on 2022-02-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staffprofile_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_number', models.CharField(blank=True, max_length=100)),
                ('names', models.CharField(blank=True, max_length=100)),
                ('Department', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, max_length=100)),
                ('end_date', models.DateField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('images', models.ImageField(default='default.jpg', upload_to='student_pics')),
            ],
        ),
    ]
