# Generated by Django 3.2.9 on 2022-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Department',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Status',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='directorate',
            field=models.CharField(blank=True, choices=[('Clinical_Services', 'Clinical Services'), ('Nursing_Services', 'Nursing Services'), ('IMIC', 'IMIC'), ('Human_Resource_Development', 'Human Resource Development'), ('Planning, Strategy & Development', 'Planning, Strategy & Development'), ('Partnerships_Linkages_&_Resource_Mobilisation', 'Partnerships, Linkages & Resource Mobilisation')], max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='directorate',
            field=models.CharField(blank=True, choices=[('Clinical_Services', 'Clinical Services'), ('Nursing_Services', 'Nursing Services'), ('IMIC', 'IMIC'), ('Human_Resource_Development', 'Human Resource Development'), ('Planning, Strategy & Development', 'Planning, Strategy & Development'), ('Partnerships_Linkages_&_Resource_Mobilisation', 'Partnerships, Linkages & Resource Mobilisation')], max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
