# Generated by Django 3.2.9 on 2022-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220215_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('AwaitingPictureTaking', 'Awaiting Picture Taking'), ('CompletedAwaitingPickup', 'Completed Awaiting Pickup'), ('Picked', 'Picked')], default='Awaiting Picture Taking', max_length=256),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('AwaitingPictureTaking', 'Awaiting Picture Taking'), ('CompletedAwaitingPickup', 'Completed Awaiting Pickup'), ('Picked', 'Picked')], default='Awaiting Picture Taking', max_length=256),
        ),
        migrations.AlterField(
            model_name='tisnstudentprofile',
            name='status',
            field=models.CharField(choices=[('AwaitingPictureTaking', 'Awaiting Picture Taking'), ('CompletedAwaitingPickup', 'Completed Awaiting Pickup'), ('Picked', 'Picked')], default='Awaiting Picture Taking', max_length=256),
        ),
    ]
